// Auto-generated by the postman-to-k6 converter

import "./libs/shim/core.js";
import "./libs/shim/expect.js";
import "./libs/shim/urijs.js";
import { sleep } from "k6";

export let options = {
scenarios: {
     load_test: {
      executor: 'ramping-vus',
      startVUs: 0,
      stages: [
        { duration: '1m', target: 10 },
        { duration: '2m', target: 30 },
	{ duration: '2m', target: 40 },
	{ duration: '2m', target: 50 },
        { duration: '1m', target: 0 },
      ],
      tags: { test_type: 'load' },
    },
  },
thresholds: {
  http_req_duration: [
    'p(95)<1000',
    'avg<500',
  ],
  http_req_failed: ['rate<0.01'],
  checks: ['rate>0.95'],
},
};

const Request = Symbol.for("request");
postman[Symbol.for("initial")]({
  options,
  environment: {
    baseUrl: "https://dummyjson.com",
    product_query: "phone",
    user_id: "6"
  }
});

export default function() {
  postman[Request]({
    name: "Get Products-List",
    id: "b2f8675f-f0b6-4468-8aa6-504ba4464e64",
    method: "GET",
    address: "{{baseUrl}}/products",
    post(response) {
      //Check if the response status code is 200
      pm.test("Status code is 200", function() {
        pm.response.to.have.status(200);
      });
      //Check if the response body contains products array
      const responseBody = pm.response.json();
      pm.test("response body contains products array", function() {
        pm.expect(responseBody).to.have.property("products");
        pm.expect(responseBody.products).to.be.an("array");
      });
        //Check if each product has required fields (id, title, price)
      pm.test("each product has required fields", function() {
        responseBody.products.forEach(product => {
          pm.expect(product).to.include.keys("id", "title", "price");
        });
      });
       //Check if each product has required fields with correct data types
      pm.test("required fields have correct data types", function() {
        responseBody.products.forEach(product => {
          pm.expect(product.id).to.be.a("number");
          pm.expect(product.title).to.be.a("string");
          pm.expect(product.price).to.be.a("number");
        });
      });
    },
tags: { endpoint: 'products_list' }
  });
sleep(5);

  postman[Request]({
    name: "Search Product-By Query",
    id: "6cb1c7ac-f51a-4a6e-b522-2528af02f8ad",
    method: "GET",
    address: "{{baseUrl}}/products/search?q={{product_query}}",
    post(response) {
      //Check if the response status code is 200
      pm.test("Status code is 200", function() {
        pm.response.to.have.status(200);
      });
      //Check if the response body contains products array
      const responseBody = pm.response.json();
      pm.test("response body contains products array", function() {
        pm.expect(responseBody).to.have.property("products");
        pm.expect(responseBody.products).to.be.an("array");
      });
      //Check if product array is not empty (for valid search)
      pm.test("search return at least one product", function() {
        pm.expect(responseBody.products.length).to.be.at.least(1);
      });
      //Check if each product has required fields (id, title, price)
      pm.test("each product has required fields", function() {
        responseBody.products.forEach(product => {
          pm.expect(product).to.include.keys("id", "title", "price");
        });
      });
      //Check if each product has required fields with correct data types
      pm.test("required fields have correct data types", function() {
        responseBody.products.forEach(product => {
          pm.expect(product.id).to.be.a("number");
          pm.expect(product.title).to.be.a("string");
          pm.expect(product.price).to.be.a("number");
        });
      });
    },
tags: { endpoint: 'search_products' }
  });
sleep(4);

  postman[Request]({
    name: "Get Carts-By User ID",
    id: "0ef7c808-e1bc-41ae-b25f-135a63da0ca8",
    method: "GET",
    address: "{{baseUrl}}/carts/user/{{user_id}}",
    post(response) {
      //Check if the response status code is 200
      pm.test("Status code is 200", function() {
        pm.response.to.have.status(200);
      });
      //Check if the response body contains the cart array
      const responseBody = pm.response.json();
      pm.test("response body conatins cart array", function() {
        pm.expect(responseBody).to.have.property("carts");
        pm.expect(responseBody.carts).to.be.an("array");
      });
      //Check if each cart contains required fields
      pm.test("each cart contains required fields", function() {
        responseBody.carts.forEach(cart => {
          pm.expect(cart).to.have.keys(
            "id",
            "products",
            "total",
            "discountedTotal",
            "userId",
            "totalProducts",
            "totalQuantity"
          );
        });
      });
    },
tags: { endpoint: 'products_by_user_id' }
  });
sleep(4);

  postman[Request]({
    name: "Add New User",
    id: "85de86df-6f7c-4813-b749-2d7f4c5f9e15",
    method: "POST",
    address: "{{baseUrl}}/users/add",
    data:
      '{\r\n    "firstName":"Rio",\r\n    "lastName":"Brown",\r\n    "age":23\r\n}',
    post(response) {
      //Check if the response status code is 201
      pm.test("Status code is 201", function() {
        pm.response.to.have.status(201);
      });
      //Check if the response body is a json object
      const responseBody = pm.response.json();
      pm.test("response body is json object", function() {
        pm.expect(responseBody).to.be.an("object");
      });
      //Check if response body has id key with correct data type
      pm.test("response body has id key and is number data type", function() {
        pm.expect(responseBody).to.have.property("id");
        pm.expect(responseBody.id).to.be.a("number");
      });
    },
tags: { endpoint: 'add_user' }
  });
sleep(2);
}
